name: Build

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - develop
      - release/**

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow

      - name: Run './build.ps1'
        run: ./build.ps1 --github-toekn $GITHUB_TOKEN --target CI
        env:
            GITHUB_TOKEN: ${{ github.toekn }}
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
          with:
            name: Artifacts
            path: Artifacts
